/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-11-10 10:41:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.net.URLEncoder;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>EasyLearn</title>\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Reset */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            background-color: #f4f4f4;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            background-color: #FFC300;\r\n");
      out.write("            padding: 10px; /* Smaller navbar */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .navbar-brand {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #000; /* Changed text color to black */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Logo size set properly */\r\n");
      out.write("        .navbar-brand img {\r\n");
      out.write("            width: 100px; /* Adjusted logo size */\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link {\r\n");
      out.write("            font-size: 18px; /* Increased font size */\r\n");
      out.write("            color: #000; /* Changed text color to black */\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link:hover {\r\n");
      out.write("            background-color: #444;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .dropdown-menu {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            min-width: 150px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .dropdown-item {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar .dropdown-item:hover {\r\n");
      out.write("            background-color: #444;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Banner */\r\n");
      out.write("        .main-banner {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-text h6 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-text h2 {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-button a {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #ff4a57;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-button a:hover {\r\n");
      out.write("            background-color: #ff2a35;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .navbar-nav {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .main-banner h2 {\r\n");
      out.write("                font-size: 36px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .main-banner h6 {\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #FFC300;\r\n");
      out.write("            color: #000; /* Changed text color to black */\r\n");
      out.write("            font-size: 16px; /* Increased font size */\r\n");
      out.write("        }\r\n");
      out.write("        .bold-text {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        HttpSession s = request.getSession(false); 
        String userName = null; 
        if (s != null) { 
            userName = (String) s.getAttribute("userName"); 
        } 
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"\"><img src=\"img.jpeg\" alt=\"Logo\"></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\"><strong>Home</strong></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                       <strong>Courses</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            ");
 
                                Connection con = null;
                                PreparedStatement ps = null;
                                ResultSet rs = null;

                                try {
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/easyleran", "root", "");

                                    String query = "SELECT course_name FROM courses ORDER BY course_name";
                                    ps = con.prepareStatement(query);
                                    rs = ps.executeQuery();

                                    while (rs.next()) { 
                            
      out.write("\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"quizinstruct.jsp?courseName=");
      out.print( URLEncoder.encode(rs.getString("course_name"), "UTF-8") );
      out.write('"');
      out.write('>');
      out.print( rs.getString("course_name") );
      out.write("</a></li>\r\n");
      out.write("                            ");
 
                                    } 
                                } catch (Exception e) {
                                    e.printStackTrace();
                            
      out.write("\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Error loading courses</a></li>\r\n");
      out.write("                            ");
 
                                } finally {
                                    if (rs != null) try { rs.close(); } catch (Exception e) { e.printStackTrace(); }
                                    if (ps != null) try { ps.close(); } catch (Exception e) { e.printStackTrace(); }
                                    if (con != null) try { con.close(); } catch (Exception e) { e.printStackTrace(); }
                                }
                            
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"profile.jsp\"><strong>Profile</strong></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"leaderboard.jsp\"><strong>Leaderboard</strong></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"feedback.jsp\"><strong>Feedback</strong></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"d-flex ms-auto\">\r\n");
      out.write("                    ");
 
                        if (userName != null) { 
                    
      out.write("\r\n");
      out.write("                      <span class=\"nav-item nav-link text-black me-3 bold-text\">");
      out.print( userName );
      out.write("</span>\r\n");
      out.write("  						<a href=\"LogoutServlet\" class=\"nav-item nav-link text-black\"><strong><i class=\"fas fa-sign-out-alt\"></i> Logout</strong></a>\r\n");
      out.write("                    ");
 
                        } else { 
                    
      out.write("\r\n");
      out.write("                        <a href=\"loginuser.jsp\" class=\"nav-item nav-link text-black\"><strong><i class=\"fas fa-sign-in-alt\"></i> Login</strong></a>\r\n");
      out.write("                    ");
 
                        } 
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"hero-section text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1 style=\"font-size: 48px; font-weight: bold;\">Welcome to EasyLearn - Learn to Code for Free!</h1>\r\n");
      out.write("        <p style=\"font-size: 20px; font-weight: bold;\">Join millions of learners from around the world on their journey to mastering coding and technology.</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"features mt-4\">\r\n");
      out.write("            <p style=\"font-size: 22px; font-weight: bold;\"><strong>Why Choose EasyLearn?</strong></p>\r\n");
      out.write("            <ul class=\"list-unstyled\" style=\"font-size: 20px; font-weight: bold;\">\r\n");
      out.write("                <li>100% Free Courses in Coding and more</li>\r\n");
      out.write("                <li>Hands-on Projects to Build Your Portfolio</li>\r\n");
      out.write("                <li>Interactive Quizzes and Challenges</li>\r\n");
      out.write("                <li>Learn from Expert Instructors and a Global Community</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"courses-section py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center mb-4\" style=\"font-size: 28px; font-weight: bold;\">Popular Courses</h2>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            ");
 
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/easyleran", "root", "");

                    String query = "SELECT course_id, course_name, description FROM courses";
                    ps = con.prepareStatement(query);
                    rs = ps.executeQuery();

                    while (rs.next()) { 
                        int courseId = rs.getInt("course_id");
                        String courseName = rs.getString("course_name");
                        String courseDescription = rs.getString("description");
            
      out.write("\r\n");
      out.write("           <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("    <div class=\"card h-100\">\r\n");
      out.write("        <!-- Using ImageServlet to display the image -->\r\n");
      out.write("        <img src=\"ImageServlet?courseId=");
      out.print( courseId );
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( courseName );
      out.write("\" style=\"width: 100%; height: 250px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\" style=\"font-size: 22px; font-weight: bold;\">");
      out.print( courseName );
      out.write("</h5>\r\n");
      out.write("            <p class=\"card-text\">");
      out.print( courseDescription );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"quizinstruct.jsp?courseName=");
      out.print( URLEncoder.encode(courseName, "UTF-8") );
      out.write("\" class=\"btn btn-primary\">Start Learning</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            ");
 
                    } 
                } catch (Exception e) {
                    e.printStackTrace();
            
      out.write("\r\n");
      out.write("            <p class=\"text-danger\">Error loading courses: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");
      out.write("            ");
 
                } finally {
                    if (rs != null) try { rs.close(); } catch (Exception e) { e.printStackTrace(); }
                    if (ps != null) try { ps.close(); } catch (Exception e) { e.printStackTrace(); }
                    if (con != null) try { con.close(); } catch (Exception e) { e.printStackTrace(); }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer class=\"text-black text-center py-3\" style=\"background-color: #FFC300; color: #000;\">\r\n");
      out.write("    <p style=\"font-size: 20px; font-weight: bold; margin: 0;\">&copy; 2024 EasyLearn. All rights reserved.</p>\r\n");
      out.write("    <p style=\"font-size: 20px; font-weight: bold; margin: 0;\">Contact us: <a href=\"\" style=\"color: #000;\">projecteasylearn1@gmail.com</a> | Phone: <a href=\"\" style=\"color: #000;\">+91 9075852242</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
